[package]
name = "ocelotl"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.10", features = ["macros"] }
sexp = "1.1.4"
nalgebra = "0.30.1"
queues = "1.0.2"
